timeout: 15min
ignore:
  - 75
  - 32
  - 78
  - 1
  - 64
  - 10
  - 67
  - 81
  - 97
  - 95
  - 92
  - 35
  - 11
  - 38
  - 6
  - 41
  - 23a
  - 23b
  - 14a
  - 14b
  - 30
  - 74
  - 87
  - 2
  - 4

dbconfig:
  max_parallel_workers: 36
  max_parallel_workers_per_gather: 36
